### ISSUE TITLE
Weapon Items Squeeze and Tear cannot be empty

### ISSUE THREAD

**Issue by TimoLemburg** [TimoLemburg/hm-gold#1]
For weapons (items) you cannot assign "" (nothing) or "-" (minus) to the aspects Squeeze and Tear to show they are not available. If you don't enter anything it is automatically filled with a 0 (zero), which implies that the weapon can in fact deliver impact by that aspect.

For the HM3 aspects Blunt, Edge and Piercing you can enter "" or "-" which leads to the inability to click on the aspect on the character sheet in the combat section which is absolutely as it should be.

**Comment by toastygm** [comment]
Use -1 to indicate that aspect is unavailable.

**Comment by TimoLemburg** [comment]
Awesome, than it's not a bug and the fields are just differently handled, kind of a cosmetic issue. I'll put that on the list of low priority doings.
